apiVersion: tarantool.io/v1alpha1
kind: Cluster
metadata:
  name: example-tarantoolcluster
spec:
  selector:
    matchLabels:
      tarantool.io/cluster-id: "example-tarantoolcluster"
  topologyService: "http://pim-topology:8081"
  topologyServiceType: "builtin"
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: topology
  namespace: default
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "vshard-router"
spec:
  selector:
    matchLabels:
      tarantool.io/role: "storage"
  replicas: 1
  serviceTemplate:
    ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
    selector:
      app: pim-storage
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: storage
  namespace: default
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "storage"
spec:
  selector:
    matchLabels:
      tarantool.io/role: "storage"
  replicas: 1
  serviceTemplate:
    ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
    selector:
      app: pim-storage
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: routers
  namespace: default
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "router"
spec:
  selector:
    matchLabels:
      tarantool.io/role: "storage"
  replicas: 1
  serviceTemplate:
    ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
    selector:
      app: pim-storage
---
apiVersion: v1
kind: Service
metadata:
  name: topology
spec:
  ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
  selector:
    tarantool.io/role: "vshard-router"
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: storage-template
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "storage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pim-storage
  volumeClaimTemplates:
  - metadata:
      name: www 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: "example-tarantoolcluster"
        app: pim-storage
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pim-storage
        image: registry.gitlab.com/tarantool/sandbox/tarantool-operator/examples/kv:latest
        volumeMounts:
          - mountPath: "/tarantool/data"
            name: www
        ports:
          - containerPort: 3301
          - containerPort: 8081
          - containerPort: 8888
        env:
          - name: TARANTOOL_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_WORK_DIR
            value: "/tarantool/data"
          - name: TARANTOOL_LOG
            value: "/tarantool/data/storage.log"
          - name: TARANTOOL_ADVERTISE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TARANTOOL_ADVERTISE_URI
            value: "$(TARANTOOL_ADVERTISE_HOST):3301"
      imagePullSecrets:
      - name: gl-regcred
