apiVersion: tarantool.io/v1alpha1
kind: TarantoolCluster
metadata:
  name: example-tarantoolcluster
spec:
  template:
    serviceName: "pim-storage"
    replicas: 3
    selector:
      matchLabels:
        app: pim-storage
    volumeClaimTemplates:
    - metadata:
        name: www
        annotations:
          volume.alpha.kubernetes.io/storage-class: "ssd"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    template:
      metadata:
        labels:
          app: pim-storage
      spec:
        terminationGracePeriodSeconds: 10
        volumes:
          - name: hostvol
            hostPath:
              path: /home/docker/tarantool
        containers:
        - name: pim-storage
          image: registry.gitlab.com/tarantool/megafon/pim:4eb1b97a
          args:
          - tarantool
          - /opt/tarantool/init.lua
          volumeMounts:
          - name: hostvol
            mountPath: /var/log/tarantool
          - mountPath: "/root/pim/data"
            name: www
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "/opt/tarantool/tarantool /opt/tarantool/devops/k8s/join.lua"]
          env:
          - name: TARANTOOL_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_MEMTX_MEMORY
            value: "1"
          - name: TARANTOOL_INSTANCE_ROLE
            value: "storage"
          - name: TARANTOOL_REPLICASET_UUID
            value: "e53fb476-be3e-49e2-ab9e-9529a932f120"
          - name: TARANTOOL_JOIN_URL
            value: "http://pim-dashboard:8081"
          - name: TARANTOOL_WORK_DIR
            value: "/root/pim/data"
          - name: TARANTOOL_ADVERTISE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TARANTOOL_ADVERTISE_URI
            value: "$(TARANTOOL_ADVERTISE_HOST):3301"
        imagePullSecrets:
        - name: gl-regcred

  # Add fields here
  size: 3
