apiVersion: tarantool.io/v1alpha1
kind: Cluster
metadata:
  name: example-tarantoolcluster
spec:
  selector:
    matchLabels:
      tarantool.io/cluster-id: "example-tarantoolcluster"
  topologyService: "http://topology:8081/admin/api"
  topologyServiceType: "builtin"
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: topology
  namespace: default
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "vshard-router"
spec:
  selector:
    matchLabels:
      tarantool.io/role: "storage"
  replicas: 1
  serviceTemplate:
    ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
    selector:
      app: pim-storage
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: storage
  namespace: default
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "storage"
spec:
  selector:
    matchLabels:
      tarantool.io/role: "storage"
  replicas: 1
  serviceTemplate:
    ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
    selector:
      app: pim-storage
---
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: routers
  namespace: default
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "router"
spec:
  selector:
    matchLabels:
      tarantool.io/role: "router"
  replicas: 1
  serviceTemplate:
    ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
    selector:
      app: pim-storage
---
apiVersion: v1
kind: Service
metadata:
  name: topology
spec:
  ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: bin
      protocol: TCP
  selector:
    tarantool.io/role: "vshard-router"
---
apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  ports:
    - port: 8081
      name: web
      protocol: TCP
  selector:
    tarantool.io/role: "router"
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: storage-template
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "storage"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pim-storage
  volumeClaimTemplates:
  - metadata:
      name: www 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: "example-tarantoolcluster"
        app: pim-storage
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pim-storage
        image: vasiliyt/tarantool-example-kv:latest
        volumeMounts:
          - mountPath: "/tarantool/data"
            name: www
        ports:
          - containerPort: 3301
          - containerPort: 8081
        env:
          - name: TARANTOOL_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_WORK_DIR
            value: "/tarantool/data"
          - name: TARANTOOL_LOG
            value: "/tarantool/data/storage.log"
          - name: TARANTOOL_ADVERTISE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TARANTOOL_ADVERTISE_URI
            value: "$(TARANTOOL_ADVERTISE_HOST):3301"
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: router-template
  labels:
    tarantool.io/cluster-id: "example-tarantoolcluster"
    tarantool.io/role: "router"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pim-router
  volumeClaimTemplates:
  - metadata:
      name: www 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: "example-tarantoolcluster"
        app: pim-router
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: pim-router
        image: vasiliyt/tarantool-example-kv:latest
        volumeMounts:
          - mountPath: "/tarantool/data"
            name: www
        ports:
          - containerPort: 3301
          - containerPort: 8081
        env:
          - name: TARANTOOL_INSTANCE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: TARANTOOL_WORK_DIR
            value: "/tarantool/data"
          - name: TARANTOOL_LOG
            value: "/tarantool/data/storage.log"
          - name: TARANTOOL_ADVERTISE_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TARANTOOL_ADVERTISE_URI
            value: "$(TARANTOOL_ADVERTISE_HOST):3301"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: examples-kv-topology
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: router
          servicePort: 8081
        path: /kv
      - backend:
          serviceName: router
          servicePort: 8081
        path: /kv_dump
      - backend:
          serviceName: topology
          servicePort: 8081
        path: /

